### ISSUE TITLE
Cannot create Stateless Service in Service Fabric injecting my own objects in

### ISSUE THREAD

**Issue by paulsaxton** [autofac/Autofac.ServiceFabric#42]
Hello

I have a Stateless service which cannot be created

```
        public ServiceFabric(StatelessServiceContext context,
            ServiceLoggerFactory serviceLoggerFactory, ServiceConfiguration configuration,
            ITrayportApiService trayportApiService)
            : base(context)
        {
//My Code here
}
```

I have used breakpoints and verified that ITrayportApiService is known about and is registered

Can someone help urgently please?

The code we use to create the container is below where UseAzureWireUp is true

```
        public static IContainer GetContainer<TServiceFabric>(string serviceFabricType, bool log = false)
            where TServiceFabric : StatelessService
        {
            if (_container == null)
            {
                var builder = new ContainerBuilder();

                try
                {
                    var moduleTypes = TypeCache.GetTypes(x => x.IsClassEx() && !x.IsAbstractEx() && x.ImplementsInterfaceEx<IModule>());

                    if (log)
                        Debug.WriteLine($"NEED TO LOG {serviceFabricType}" );


                    foreach (var moduleType in moduleTypes)
                    {
                        var module = Activator.CreateInstance(moduleType) as IModule;
                        if (module != null)
                        {
                            if (log)
                                Debug.WriteLine($"{serviceFabricType} {moduleType.Name}");

                            builder.RegisterModule(module);
                        }
                    }



                }
                catch (Exception e)
                {
                    Debug.WriteLine(e);
                    throw;
                }
                if (UseAzureWireup)
                {
                    builder.RegisterServiceFabricSupport();

                    // This needs to match the name of the type in 
                    // PackageRoot\ServiceManifest.xml AND ApplicationPackageRoot\ApplicationManifest
                    builder.RegisterStatelessService<TServiceFabric>(serviceFabricType);
                }

                var container = builder.Build();

                // To make sure the logger is being instantiated, resolve it
                var logger = container.Resolve<ILogger>();

                _container = container;
            }

            return _container;
        }
```

Paul

The message is below

I cant get the inner exception details which is annoying!

Unhealthy event: SourceId='System.RA', Property='ReplicaOpenStatus', HealthState='Warning', ConsiderWarningAsError=false.
Replica had multiple failures during open on _Node_0. API call: IStatelessServiceInstance.Open(); Error = Autofac.Core.DependencyResolutionException (-2146233088)
An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ServiceFabricProxy (DelegateActivator), Services = [Inspired.TradingPlatform.TrayportApi.Primary.ServiceFabric.ServiceFabric], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner except
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Integration.ServiceFabric.StatelessServiceFactoryRegistration.<>c__DisplayClass0_0`1.b__0(StatelessServiceContext context)
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceFactory.System.Fabric.IStatelessServiceFactory.CreateInstance(String serviceTypeName, Uri serviceName, Byte[] initializationData, Guid partitionId, Int64 instanceId)
   at System.Fabric.ServiceFactoryBroker.<>c__DisplayClass9_0.b__0(IStatelessServiceFactory factory, ServiceInitializationParameters initParams)
   at System.Fabric.ServiceFactoryBroker.CreateHelper[TFactory,TReturnValue](IntPtr nativeServiceType, IntPtr nativeServiceName, UInt32 initializationDataLength, IntPtr nativeInitializationData, Guid partitionId, Func`3 creationFunc, Action`2 initializationFunc, ServiceInitializationParameters initializationParameters)
For more information see: http://aka.ms/sfhealth

**Comment by alexmg** [comment]
You will be able to provide an `Action<Exception>` to the `ServiceFabricModule` in the next release which should help with debugging these scenarios.

**Comment by alexmg** [comment]
The `2.1.0` release is now available on NuGet.
