### ISSUE TITLE
Unable to resolve ServiceContext for dependent component

### ISSUE THREAD

**Issue by vikramadhav** [autofac/Autofac.ServiceFabric#7]
Thanks for coming up with solution to do dependency injection, but facing an issue while trying to resolve to service context to dependent class,
While doing an exercise, I created a stateless service , 
like
```
 public Stateless1(StatelessServiceContext context, IConfigSettingsProvider configSettingsProvider)
{
//
}

 IConfigSettingsProvider
{
ConfigSettingsProvider(StatefulServiceContext context);
ConfigSettingsProvider(StatelessServiceContext context)
}

Program.cs

                 var builder = new ContainerBuilder();

                builder.Register(ctx =>
                {
                    var context = ctx.Resolve<StatelessServiceContext>();
                    return new ConfigSettingsProvider(context);

                }).As<IConfigSettingsProvider>().SingleInstance();


```
Exception: 

```
Autofac.Core.Registration.ComponentNotRegisteredException was unhandled by user code
  HResult=-2146233088
  Message=The requested service 'System.Fabric.StatelessServiceContext' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
  Source=Autofac
  StackTrace:
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
       at Stateless1.Program.<>c.<Main>b__0_0(IComponentContext ctx) in C:\WorkingFolder\Spike\DITesting\Stateless1\Program.cs:line 22
       at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p)
       at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
  InnerException: 
```

I understand the problem here but How do I resolve the context?

**Comment by vikramadhav** [comment]
This already addressed in other issue, Apologies for oversight
